name: bloc_enhancer
description: An annotation package simplifying Bloc event and state classes, enhancing code readability and reducing naming conflicts.

homepage: https://github.com/Couchsurfing/dart-bloc-enhancer
repository: https://github.com/Couchsurfing/dart-bloc-enhancer
issue_tracker: https://github.com/Couchsurfing/dart-bloc-enhancer/issues

topics: ["bloc", "code-generation", "enhance", "state"]

version: 0.5.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ">=1.0.0 <2.0.0"

dev_dependencies:
  equatable: ^2.0.5
  lints: ">=2.1.1 <4.0.0"
  test: ^1.21.5
